language: go

go:
  - 1.6
  - tip

services:
  - postgresql

before_script:
  - psql -c 'CREATE USER pgtest;' -U postgres
  - psql -c 'CREATE DATABASE pgtest OWNER pgtest;' -U postgres

script:
  - go get -u github.com/mattn/gom 
  - gom install
  - go test -v
