language: go

go:
  - 1.11
  - tip

services:
  - postgresql

before_script:
  - psql -c 'CREATE USER pgtxdbtest;' -U postgres
  - psql -c 'CREATE DATABASE pgtxdbtest OWNER pgtxdbtest;' -U postgres

script:
  - go get -u github.com/mattn/gom 
  - gom install
  - go test -v
